[package]
name = "jito-transaction-relayer"
version = "0.1.0"
description = "Solana Transaction Relayer"
authors = ["Jito Team <team@jito.wtf>"]
homepage = "https://jito.wtf/"
edition = "2021"
publish = false

[dependencies]
bincode = "1.3.3"
clap = { version = "3.1.12", features = ["derive", "env"] }
crossbeam-channel = "0.5.5"
ctrlc = "3.2.3"
env_logger = "0.9.0"
itertools = "0.10.3"
jito-block-engine = { path = "../block_engine", version = "0.1.0" }
jito-core = { path = "../core" }
jito-protos = { path = "../jito-protos" }
jito-relayer = { path = "../relayer" }
jito-rpc = { path = "../rpc" }
jwt = { version = "0.16.0", features = ["openssl"] }
log = "0.4.14"
openssl = "0.10.41"
prost-types = "0.10.1"
reqwest = "0.11.13"
solana-core = "=1.14.11"
solana-metrics = "=1.14.11"
solana-net-utils = "=1.14.11"
solana-perf = "=1.14.11"
solana-sdk = "=1.14.11"
tokio = { version = "1.14.1", features = ["rt-multi-thread"] }
tokio-stream = "0.1.8"
tonic = "0.7.2"
