[package]
name = "jito-packet-blaster"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = { version = "3.1.12", features = ["derive", "env"] }
env_logger = "0.9.0"
log = "0.4.17"
solana-client = "=1.14.11"
solana-perf = "=1.14.11"
solana-sdk = "=1.14.11"
tokio = { version = "1.14.1", features = ["rt-multi-thread"] }
