[package]
name = "jito-block-engine"
version = "0.1.0"
description = "Relayer Block Engine Client"
authors = ["Jito Team <team@jito.wtf>"]
homepage = "https://jito.wtf/"
edition = "2021"
publish = false

[dependencies]
jito-protos = { path = "../jito-protos" }
log = "0.4.17"
prost-types = "0.10.1"
solana-perf = "=1.11.5"
solana-sdk = "=1.11.5"
thiserror = "1.0.31"
tokio = { version = "1.14.1", features = ["full"] }
tokio-stream = "0.1.9"
tonic = "0.7.2"
solana-metrics = "=1.11.5"