[package]
name = "jito-relayer"
version = "0.1.0"
description = "Relayer GRPC server"
authors = ["Jito Team <team@jito.wtf>"]
homepage = "https://jito.wtf/"
edition = "2021"
publish = false

[dependencies]
crossbeam-channel = "0.5.4"
jito-protos = { path = "../jito-protos" }
jito-rpc = { path = "../rpc" }
log = "0.4.17"
solana-sdk = "1.10.24"
solana-client = "1.10.24"
solana-core = "1.10.24"
solana-perf = "1.10.24"
tokio-stream = "0.1.9"
tokio = { version = "1.14.1", features = ["time"] }
tonic = "0.7.2"
