[package]
name = "jito-relayer"
version = "0.1.0"
description = "Relayer GRPC server"
authors = ["Jito Team <team@jito.wtf>"]
homepage = "https://jito.wtf/"
edition = "2021"
publish = false

[dependencies]
bitvec = "1"
crossbeam-channel = "0.5.4"
ed25519-dalek = "1.0.1"
futures-util = "0.3"
jito-protos = { path = "../jito-protos" }
jito-rpc = { path = "../rpc" }
prost-types = "0.10.1"
log = "0.4.17"
solana-client = "=1.10.25"
solana-core = "=1.10.25"
solana-metrics = "=1.10.25"
solana-perf = "=1.10.25"
solana-sdk = "=1.10.25"
thiserror = "1.0"
tokio = { version = "1.14.1", features = ["time"] }
tokio-stream = "0.1.9"
tonic = "0.7.2"
